destinations:
  # Website 1
  - baseUrl:
    routes: https://google.com
      - path: /
        method: GET
      - path: /preferences
        method:
        expectedStatusCode:
  # Website 2
  - baseUrl:
    routes:
      - path:
        method:
        headers:
          -
      - path:
        method:
        expectedStatusCode:
  # Website 3
  - baseUrl:
    routes:
      - path:
        method:
        expectedStatusCode:
        headers:
          -
